-- Decompiled with Potassium's decompiler.

local l__Plants__1 = game:GetService("ReplicatedStorage"):WaitForChild("Assets"):WaitForChild("Plants");
local l__SeedImages__2 = script.SeedImages;
local _ = script.PlantImages;
local l__FruitImages__3 = script.FruitImages;
return {
    {
        SeedName = "Carrot",
        PurchasePrice = 1,
        RestockShop = true,
        SeedShopDisplayOrder = 1,
        YHeight = 2,
        RestockChance = 100,
        IsSingleHarvest = true,
        Rarity = "Common",
        PrimeTime = 60,
        SeedImage = l__SeedImages__2.Carrot,
        FruitImage = l__FruitImages__3.Carrot,
        RestockValues = NumberRange.new(3, 4),
        PlantModel = l__Plants__1:WaitForChild("Carrot")
    },
    {
        SeedName = "Strawberry",
        PurchasePrice = 10,
        RestockShop = true,
        SeedShopDisplayOrder = 2,
        YHeight = 1,
        RestockChance = 100,
        IsSingleHarvest = false,
        Rarity = "Common",
        PrimeTime = 90,
        SeedImage = l__SeedImages__2.Strawberry,
        FruitImage = l__FruitImages__3.Strawberry,
        RestockValues = NumberRange.new(4, 5),
        PlantModel = l__Plants__1:WaitForChild("Strawberry")
    },
    {
        SeedName = "Blueberry",
        PurchasePrice = 25,
        RestockShop = true,
        SeedShopDisplayOrder = 3,
        YHeight = 1,
        RestockChance = 100,
        IsSingleHarvest = false,
        Rarity = "Common",
        PrimeTime = 90,
        SeedImage = l__SeedImages__2.Blueberry,
        FruitImage = l__FruitImages__3.Blueberry,
        RestockValues = NumberRange.new(1, 2),
        PlantModel = l__Plants__1:WaitForChild("Blueberry")
    },
    {
        SeedName = "Tulip",
        PurchasePrice = 40,
        RestockShop = true,
        SeedShopDisplayOrder = 4,
        YHeight = 0,
        RestockChance = 100,
        IsSingleHarvest = true,
        Rarity = "Uncommon",
        PrimeTime = 60,
        SeedImage = l__SeedImages__2.Tulip,
        FruitImage = l__FruitImages__3.Tulip,
        RestockValues = NumberRange.new(3, 4),
        PlantModel = l__Plants__1:WaitForChild("Tulip")
    },
    {
        SeedName = "Tomato",
        PurchasePrice = 200,
        RestockShop = true,
        SeedShopDisplayOrder = 5,
        YHeight = 1,
        RestockChance = 90,
        IsSingleHarvest = false,
        Rarity = "Uncommon",
        PrimeTime = 120,
        SeedImage = l__SeedImages__2.Tomato,
        FruitImage = l__FruitImages__3.Tomato,
        RestockValues = NumberRange.new(2, 3),
        PlantModel = l__Plants__1:WaitForChild("Tomato")
    },
    {
        SeedName = "Apple",
        PurchasePrice = 400,
        RestockShop = true,
        SeedShopDisplayOrder = 6,
        YHeight = 1,
        RestockChance = 52.63,
        IsSingleHarvest = false,
        Rarity = "Uncommon",
        PrimeTime = 180,
        SeedImage = l__SeedImages__2.Apple,
        FruitImage = l__FruitImages__3.Apple,
        RestockValues = NumberRange.new(1, 1),
        PlantModel = l__Plants__1:WaitForChild("Apple")
    },
    {
        SeedName = "Bamboo",
        PurchasePrice = 700,
        RestockShop = true,
        SeedShopDisplayOrder = 7,
        YHeight = 7,
        RestockChance = 80,
        IsSingleHarvest = true,
        Rarity = "Rare",
        PrimeTime = 120,
        SeedImage = l__SeedImages__2.Bamboo,
        FruitImage = l__FruitImages__3.Bamboo,
        RestockValues = NumberRange.new(7, 11),
        PlantModel = l__Plants__1:WaitForChild("Bamboo")
    },
    {
        SeedName = "Corn",
        PurchasePrice = 2500,
        RestockShop = true,
        SeedShopDisplayOrder = 8,
        YHeight = 2,
        RestockChance = 35,
        IsSingleHarvest = false,
        Rarity = "Rare",
        PrimeTime = 240,
        SeedImage = l__SeedImages__2.Corn,
        FruitImage = l__FruitImages__3.Corn,
        RestockValues = NumberRange.new(1, 1),
        PlantModel = l__Plants__1:WaitForChild("Corn")
    },
    {
        SeedName = "Cactus",
        PurchasePrice = 5000,
        RestockShop = true,
        SeedShopDisplayOrder = 9,
        YHeight = 3,
        RestockChance = 16.668,
        IsSingleHarvest = false,
        Rarity = "Rare",
        PrimeTime = 240,
        SeedImage = l__SeedImages__2.Cactus,
        FruitImage = l__FruitImages__3.Cactus,
        RestockValues = NumberRange.new(1, 2),
        PlantModel = l__Plants__1:WaitForChild("Cactus")
    },
    {
        SeedName = "Pineapple",
        PurchasePrice = 10000,
        RestockShop = true,
        SeedShopDisplayOrder = 10,
        YHeight = 7,
        RestockChance = 12.501,
        IsSingleHarvest = false,
        Rarity = "Rare",
        PrimeTime = 300,
        SeedImage = l__SeedImages__2.Pineapple,
        FruitImage = l__FruitImages__3.Pineapple,
        RestockValues = NumberRange.new(1, 3),
        PlantModel = l__Plants__1:WaitForChild("Pineapple")
    },
    {
        SeedName = "Mushroom",
        PurchasePrice = 15000,
        RestockShop = true,
        SeedShopDisplayOrder = 11,
        YHeight = 7,
        RestockChance = 9.092,
        IsSingleHarvest = true,
        Rarity = "Epic",
        PrimeTime = 360,
        SeedImage = l__SeedImages__2.Mushroom,
        FruitImage = l__FruitImages__3.Mushroom,
        RestockValues = NumberRange.new(2, 5),
        PlantModel = l__Plants__1:WaitForChild("Mushroom")
    },
    {
        SeedName = "Green Bean",
        PurchasePrice = 20000,
        RestockShop = true,
        SeedShopDisplayOrder = 12,
        YHeight = 7,
        RestockChance = 15,
        IsSingleHarvest = true,
        Rarity = "Epic",
        PrimeTime = 360,
        SeedImage = l__SeedImages__2["Green Bean"],
        FruitImage = l__FruitImages__3["Green Bean"],
        RestockValues = NumberRange.new(1, 2),
        PlantModel = l__Plants__1:WaitForChild("Green Bean")
    },
    {
        SeedName = "Banana",
        PurchasePrice = 30000,
        RestockShop = true,
        SeedShopDisplayOrder = 13,
        YHeight = 2,
        RestockChance = 9,
        IsSingleHarvest = false,
        Rarity = "Epic",
        PrimeTime = 240,
        SeedImage = l__SeedImages__2.Banana,
        FruitImage = l__FruitImages__3.Banana,
        RestockValues = NumberRange.new(1, 1),
        PlantModel = l__Plants__1:WaitForChild("Banana")
    },
    {
        SeedName = "Grape",
        PurchasePrice = 50000,
        RestockShop = true,
        SeedShopDisplayOrder = 14,
        YHeight = 5,
        RestockChance = 6.668,
        IsSingleHarvest = false,
        Rarity = "Epic",
        PrimeTime = 420,
        SeedImage = l__SeedImages__2.Grape,
        FruitImage = l__FruitImages__3.Grape,
        RestockValues = NumberRange.new(1, 1),
        PlantModel = l__Plants__1:WaitForChild("Grape")
    },
    {
        SeedName = "Coconut",
        PurchasePrice = 70000,
        RestockShop = true,
        SeedShopDisplayOrder = 15,
        YHeight = 4,
        RestockChance = 5.001,
        IsSingleHarvest = false,
        Rarity = "Epic",
        PrimeTime = 480,
        SeedImage = l__SeedImages__2.Coconut,
        FruitImage = l__FruitImages__3.Coconut,
        RestockValues = NumberRange.new(1, 1),
        PlantModel = l__Plants__1:WaitForChild("Mango")
    },
    {
        SeedName = "Mango",
        PurchasePrice = 85000,
        RestockShop = true,
        SeedShopDisplayOrder = 16,
        YHeight = 4,
        RestockChance = 5.001,
        IsSingleHarvest = false,
        Rarity = "Epic",
        PrimeTime = 480,
        SeedImage = l__SeedImages__2.Mango,
        FruitImage = l__FruitImages__3.Mango,
        RestockValues = NumberRange.new(1, 1),
        PlantModel = l__Plants__1:WaitForChild("Mango")
    },
    {
        SeedName = "Dragon Fruit",
        PurchasePrice = 120000,
        RestockShop = true,
        SeedShopDisplayOrder = 17,
        YHeight = 4,
        RestockChance = 4,
        IsSingleHarvest = false,
        Rarity = "Legendary",
        PrimeTime = 480,
        SeedImage = l__SeedImages__2["Dragon Fruit"],
        FruitImage = l__FruitImages__3["Dragon Fruit"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = l__Plants__1:WaitForChild("Dragon Fruit")
    },
    {
        SeedName = "Acorn",
        PurchasePrice = 200000,
        RestockShop = true,
        SeedShopDisplayOrder = 18,
        YHeight = 4,
        RestockChance = 2.942,
        IsSingleHarvest = false,
        Rarity = "Legendary",
        PrimeTime = 600,
        SeedImage = l__SeedImages__2.Acorn,
        FruitImage = l__FruitImages__3.Acorn,
        RestockValues = NumberRange.new(1, 3),
        PlantModel = l__Plants__1:WaitForChild("Acorn")
    },
    {
        SeedName = "Cherry",
        PurchasePrice = 250000,
        RestockShop = true,
        SeedShopDisplayOrder = 19,
        YHeight = 2,
        RestockChance = 2.274,
        IsSingleHarvest = false,
        Rarity = "Legendary",
        PrimeTime = 660,
        SeedImage = l__SeedImages__2.Cherry,
        FruitImage = l__FruitImages__3.Cherry,
        RestockValues = NumberRange.new(1, 1),
        PlantModel = l__Plants__1:WaitForChild("Cherry")
    },
    {
        SeedName = "Sunflower",
        PurchasePrice = 300000,
        RestockShop = true,
        SeedShopDisplayOrder = 20,
        YHeight = 1,
        RestockChance = 1.787,
        IsSingleHarvest = false,
        Rarity = "Legendary",
        PrimeTime = 720,
        SeedImage = l__SeedImages__2.Sunflower,
        FruitImage = l__FruitImages__3.Sunflower,
        RestockValues = NumberRange.new(1, 1),
        PlantModel = l__Plants__1:WaitForChild("Sunflower")
    },
    {
        SeedName = "Venus Fly Trap",
        PurchasePrice = 400000,
        RestockShop = true,
        SeedShopDisplayOrder = 21,
        YHeight = 2,
        RestockChance = 1.43,
        IsSingleHarvest = false,
        Rarity = "Mythic",
        PrimeTime = 900,
        SeedImage = l__SeedImages__2["Venus Fly Trap"],
        FruitImage = l__FruitImages__3["Venus Fly Trap"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = l__Plants__1:WaitForChild("Venus Fly Trap")
    },
    {
        SeedName = "Pomegranate",
        PurchasePrice = 2000000,
        RestockShop = true,
        SeedShopDisplayOrder = 22,
        YHeight = 2,
        RestockChance = 0.927,
        IsSingleHarvest = false,
        Rarity = "Mythic",
        PrimeTime = 1200,
        SeedImage = l__SeedImages__2.Pomegranate,
        FruitImage = l__FruitImages__3.Pomegranate,
        RestockValues = NumberRange.new(1, 1),
        PlantModel = l__Plants__1:WaitForChild("Pomegranate")
    },
    {
        SeedName = "Poison Apple",
        PurchasePrice = 400000,
        RestockShop = true,
        SeedShopDisplayOrder = 23,
        YHeight = 2,
        RestockChance = 0.533,
        IsSingleHarvest = false,
        Rarity = "Mythic",
        PrimeTime = 1800,
        SeedImage = l__SeedImages__2["Poison Apple"],
        FruitImage = l__FruitImages__3["Poison Apple"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = l__Plants__1:WaitForChild("Poison Apple")
    },
    {
        SeedName = "Moon Bloom",
        PurchasePrice = 7000000,
        RestockShop = true,
        SeedShopDisplayOrder = 24,
        YHeight = 0,
        RestockChance = 0.35,
        IsSingleHarvest = false,
        Rarity = "Super",
        PrimeTime = 240,
        SeedImage = l__SeedImages__2["Moon Bloom"],
        FruitImage = l__FruitImages__3["Moon Bloom"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = l__Plants__1:WaitForChild("Moon Bloom")
    },
    {
        SeedName = "Dragon\'s Breath",
        PurchasePrice = 9000000,
        RestockShop = true,
        SeedShopDisplayOrder = 25,
        YHeight = 0,
        RestockChance = 0.275,
        IsSingleHarvest = false,
        Rarity = "Super",
        PrimeTime = 240,
        SeedImage = l__SeedImages__2["Dragon\'s Breath"],
        FruitImage = l__FruitImages__3["Dragon\'s Breath"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = l__Plants__1:WaitForChild("Dragon\'s Breath")
    },
    {
        SeedName = "Ghost Pepper",
        PurchasePrice = 2800000,
        RestockShop = false,
        SeedShopDisplayOrder = 26,
        YHeight = 2,
        RestockChance = 0.533,
        IsSingleHarvest = false,
        Rarity = "Mythic",
        PrimeTime = 1800,
        SeedImage = l__SeedImages__2["Ghost Pepper"],
        FruitImage = l__FruitImages__3["Ghost Pepper"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = l__Plants__1:WaitForChild("Ghost Pepper")
    },
    {
        SeedName = "Poison Ivy",
        PurchasePrice = 2800000,
        RestockShop = false,
        SeedShopDisplayOrder = 27,
        YHeight = 2,
        RestockChance = 0.533,
        IsSingleHarvest = false,
        Rarity = "Legendary",
        PrimeTime = 1800,
        SeedImage = l__SeedImages__2["Poison Ivy"],
        FruitImage = l__FruitImages__3["Poison Ivy"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = l__Plants__1:WaitForChild("Poison Ivy")
    },
    {
        SeedName = "Baby Cactus",
        PurchasePrice = 1,
        RestockShop = false,
        SeedShopDisplayOrder = 27,
        YHeight = 2,
        RestockChance = 0.533,
        IsSingleHarvest = false,
        Rarity = "Rare",
        PrimeTime = 240,
        SeedImage = l__SeedImages__2["Baby Cactus"],
        FruitImage = l__FruitImages__3["Baby Cactus"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = l__Plants__1:WaitForChild("Baby Cactus")
    },
    {
        SeedName = "Glow Mushroom",
        PurchasePrice = 1,
        RestockShop = false,
        SeedShopDisplayOrder = 28,
        YHeight = 2,
        RestockChance = 0.533,
        IsSingleHarvest = false,
        Rarity = "Epic",
        PrimeTime = 240,
        SeedImage = l__SeedImages__2["Glow Mushroom"],
        FruitImage = l__FruitImages__3["Glow Mushroom"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = l__Plants__1:WaitForChild("Glow Mushroom")
    },
    {
        SeedName = "Romanesco",
        PurchasePrice = 1,
        RestockShop = false,
        SeedShopDisplayOrder = 29,
        YHeight = 2,
        RestockChance = 0.533,
        IsSingleHarvest = false,
        Rarity = "Mythic",
        PrimeTime = 240,
        SeedImage = l__SeedImages__2.Romanesco,
        FruitImage = l__FruitImages__3.Romanesco,
        RestockValues = NumberRange.new(1, 1),
        PlantModel = l__Plants__1:WaitForChild("Romanesco")
    },
    {
        SeedName = "Horned Melon",
        PurchasePrice = 1,
        RestockShop = false,
        SeedShopDisplayOrder = 30,
        YHeight = 2,
        RestockChance = 0.533,
        IsSingleHarvest = false,
        Rarity = "Rare",
        PrimeTime = 240,
        SeedImage = l__SeedImages__2["Horned Melon"],
        FruitImage = l__FruitImages__3["Horned Melon"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = l__Plants__1:WaitForChild("Horned Melon")
    },
    {
        SeedName = "Gold",
        MutationSeed = true,
        RestockShop = false,
        YHeight = 2,
        Rarity = "Legendary",
        SeedImage = l__SeedImages__2.Gold
    },
    {
        SeedName = "Rainbow",
        MutationSeed = true,
        RestockShop = false,
        YHeight = 2,
        Rarity = "Mythic",
        SeedImage = l__SeedImages__2.Rainbow
    },
    {
        SeedName = "Green Bean",
        PurchasePrice = 1,
        RestockShop = false,
        SeedShopDisplayOrder = 26,
        YHeight = 2,
        RestockChance = 0.533,
        IsSingleHarvest = false,
        Rarity = "Epic",
        PrimeTime = 240,
        SeedImage = l__SeedImages__2["Green Bean"],
        FruitImage = l__FruitImages__3["Green Bean"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = l__Plants__1:WaitForChild("Green Bean")
    }
};